### ISSUE TITLE
支持Epoll

### ISSUE THREAD

**Issue by medusar** [szhnet/kcp-netty#12]
目前kcp-netty通过一个线程维护所有客户端的kcp_update方法调用，同时该线程还要负责数据读取、数据下发、数据在pipeline中传递。
担心如果连接的客户端量太大，一个线程将无法满足需求。
如该[issue](https://github.com/netty/netty/issues/1706)所说的，如果支持Epoll的方式，可以通过设置`EpollChannelOption.SO_REUSEPORT`为true的方式多次绑定同一个端口，这样就可以通过多个线程来支持更多的连接。

**Comment by szhnet** [comment]
嗯，是有这个问题，#7里也提到过。我这边是多开端口的，所以并没有受到这方面的困扰。你提到的Epoll方式我之后有时间会研究一下。如果你很需要使用Epoll，你也可以考虑自己实现一下。

**Comment by medusar** [comment]
了解了，谢谢！

**Comment by medusar** [comment]
Let me close this.

**Comment by dslchd** [comment]
@medusar 请问你们是否用一个for 来循环绑定同一个端口来解决这个问题的吗?
但这个方案是不是仅限linux环境使用?
如果是开多个端口，那么客户端随机访问服务端某一个端口吗？

**Comment by medusar** [comment]
@dslchd Netty本身提供了支持同一个端口绑定多次的机制，但是需要使用Epoll相关的类，目前kcp-netty没有支持该机制，的确，该机制仅限linux使用。目前我们是计划绑定多个端口的方式，客户端连接哪个端口可以通过服务端下发控制。

**Comment by dslchd** [comment]
@medusar thank you! 绑定多个端口 可以和客户端约定一下。
