### ISSUE TITLE
当客户端发包速度过快时，服务端只收到一部分消息包

### ISSUE THREAD

**Issue by vovgou** [szhnet/kcp-netty#26]
你好，想咨询一个问题，我使用极速模式，客户端和服务器配置： ikcp_nodelay(kcp, 1, 10, 2, 1); ，MTU：512，RCV_WND和SND_WND为64，当我在客户端循环发送100个包，
for (int i = 0; i < 100; i++) {
    ChannelFuture future = channel.writeAndFlush(request);
    future.sync();
｝

我的服务器只收到了前面的60多个包，后面的包全丢了，当我每发送一个包，睡眠5毫秒，则服务器能收到所有的100个包。这应该是发送窗口满了，消息丢了。请问下，future.sync() 无法阻塞，直到SND_WND 清空吗？

**Comment by szhnet** [comment]
是的 future.sync() 无法一直阻塞到 SND_WND 清空？调用 kcp 的 send 方法后，future 就不阻塞了。
