### ISSUE TITLE
发送包太大的bug

### ISSUE THREAD

**Issue by foolin** [szhnet/kcp-netty#31]
发送一个超大的数据包，直接抛java.io.IOException: Too many fragments

```
    /**
     * Sends a Bytebuf.
     *
     * @param buf
     * @throws IOException
     */
    public void send(ByteBuf buf) throws IOException {
        int ret = kcp.send(buf);
        switch (ret) {
            case -2:
                throw new IOException("Too many fragments");
            default:
                break;
        }
    }
```

```
        if (count >= IKCP_WND_RCV) { // Maybe don't need the conditon in stream mode
            return -2;
        }
```

出错是这个地方，这里直接可以把if条件去掉？

![image](https://user-images.githubusercontent.com/2344587/143449729-096bafd4-f1d2-4121-bc4a-45fa48eb2b6e.png)

**Comment by szhnet** [comment]
kcp 这里就是这么写的 https://github.com/skywind3000/kcp/blob/58139efbbaa6fc82a451b780b05d37fb41f21d15/ikcp.c#L510 。不过我觉得这里应该是判断 >= 256 更合理，因为 segment 的 frg 字段大小是一个字节。而且应该只在非流模式下才应该判断。

**Comment by szhnet** [comment]
我改了一下，已更新到v1.5.0
